version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  orchestrator:
    build: ./orchestrator
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "pgmq"
      POSTGRES_DB: "pgmq"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: